#!/bin/bash

# ----------------------------------------------------------------------------------------
# Power off Wi-Fi when go to sleep
#
#
# 说明：
#    使用
#
# 参考：
#    sleepwatcher：http://www.bernhard-baehr.de
#    http://tyhoffman.com/blog/2013/09/sleepwatcher-power-event-driven-automation
#
# Uninstall:
#    sudo /Library/Application\ Support/offWiFiSleep/uninstall.sh
#
# Install:
#    install the package
#
# Version:
#    1.0.1 Initial release
#    1.1.0 minior fixes
#
# Author:
#    Tony Liu, 2017-
#    TonyLiu2ca@yahoo.com
# ----------------------------------------------------------------------------------------
# Set permissions
chmod -RN /Library/offWiFiSleep
chflags -R schg /Library/offWiFiSleep/.sleep
chflags -R schg /Library/offWiFiSleep/.wakeup
chmod 777 /Library/offWiFiSleep/offWiFiSleep_Settings.ini

# clean up others
/bin/launchctl unload -w /Library/LaunchDaemons/de.bernhard-baehr.sleepwatcher.plist &>/dev/null
rm -f /Library/LaunchDaemons/de.bernhard-baehr.sleepwatcher.plist &>/dev/null
rm -f /etc/rc.sleep /etc/rc.wakeup &>/dev/null
rm -fr /Library/Application\ Support/offWiFiSleep &>/dev/null

/bin/launchctl unload -w /Library/LaunchDaemons/com.github.TonyLiu2ca.offWiFiSleep.plist &>/dev/null
chmod 644 /Library/LaunchDaemons/com.github.TonyLiu2ca.offWiFiSleep.plist
chown root:wheel /Library/LaunchDaemons/com.github.TonyLiu2ca.offWiFiSleep.plist
/bin/launchctl load -w /Library/LaunchDaemons/com.github.TonyLiu2ca.offWiFiSleep.plist &>/dev/null
exit 0