#!/bin/bash

# ----------------------------------------------------------------------------------------
# Power off Wi-Fi when go to sleep
#
#
# 说明：
#    使用
#
# 参考：
#    sleepwatcher：http://www.bernhard-baehr.de
#    http://tyhoffman.com/blog/2013/09/sleepwatcher-power-event-driven-automation
#
# Uninstall:
#    sudo /Library/Application\ Support/offWiFiSleep/uninstall.sh
#
# Install:
#    install the package
#
# Version:
#    1.0.1
#    
# Author:
#    Tony Liu, 2017-
#    TonyLiu2ca@yahoo.com
# ----------------------------------------------------------------------------------------
chmod -RN ./root/Library/Application\ Support/offWiFiSleep
chflags -R schg ./root/Library/Application\ Support/offWiFiSleep/.sleep
chflags -R schg ./root/Library/Application\ Support/offWiFiSleep/.wakeup
chmod 777 ./root/Library/Application\ Support/offWiFiSleep/offWiFiSleep_Settings.ini
#rm -f ./scripts/.DS_Store
rm -f /Library/LaunchDaemons/de.bernhard-baehr.sleepwatcher.plist 

# remove others
/bin/launchctl unload -w /Library/LaunchDaemons/de.bernhard-baehr.sleepwatcher.plist 1>&- 2>&1
rm -f /etc/rc.sleep /etc/rc.wakeup  1>&- 2>&1

/bin/launchctl unload -w /Library/LaunchDaemons/com.github.TonyLiu2ca.offWiFiSleep.plist 1>&- 2>&1
chmod 644 /Library/LaunchDaemons/com.github.TonyLiu2ca.offWiFiSleep.plist
chown root:wheel /Library/LaunchDaemons/com.github.TonyLiu2ca.offWiFiSleep.plist
/bin/launchctl load -w /Library/LaunchDaemons/com.github.TonyLiu2ca.offWiFiSleep.plist 1>&- 2>&1
exit 0